### ISSUE TITLE
Scenario testing report

### ISSUE THREAD

**Issue by Isan-Rivkin** [similarweb/statusbay#40]
# Deploy Once 

Launch Statusbay from scratch and deploy each time different resources. 

### Sunny day tests 

- [x] Daemonset
- [x] Deployment
- [ ] StatefulSet 
- [ ] All Together 

# Redeploy Running  

Redeploy resources to Statusbay as a rollout to new version.

### Sunny day tests 

- [x] Daemonset
- [x] Deployment
- [ ] StatefulSet 
- [ ] All Together 

# Redeploy Deleted  

Redeploy resources to Statusbay on previously deployed and now-deleted resources. 

### Sunny day tests 

- [x] Daemonset
- [x] Deployment
- [ ] StatefulSet 
- [ ] All Together 

# Delete 

Delete running resources. 

- [x] Daemonset
- [x] Deployment
- [ ] StatefulSet 
- [ ] All Together 

# Miscellaneous
- [x] "Invalid log level, not setting" error when starting the watcher.   @cregev pr #37 
- [x] slack always sends "task deleted" fixed at pr #42 @Isan-Rivkin 
- [x] Deploy an application with a different image when the application is still deploy
- [x] examples yaml: when using `daemonset.count` or `deployment.count`  bigger than 1 it only creates 1 no matter what.  fixes #43 
- [x] use `-race` flag  **BUG** issue #49 
- [x] race condition on deployment status  **BUG** issue #50 
- [x] Delete when deployment is running **BUG** issue: #47 
- [x] Restart watcher while deployments are in "running" state **BUG** issue #48 
- [ ] Deployment finish by still waiting for the `collect_data_after_apply_finish`, at the waiting time try to redeploy new image. @kaplanelad please elaborate in an issue.
